name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Exchange keys for app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_BOT_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Get GitHub App User information
        id: user-info
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          ID=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)
          NAME="${{ steps.app-token.outputs.app-slug }}[bot]"
          EMAIL="$ID+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          AUTHOR="$NAME <$EMAIL>"

          echo "user-id=$ID" >> "$GITHUB_OUTPUT"
          echo "user-name=$NAME" >> "$GITHUB_OUTPUT"
          echo "user-email=$EMAIL" >> "$GITHUB_OUTPUT"
          echo "git-author=$AUTHOR" >> "$GITHUB_OUTPUT"

      - name: Set Git author
        run: |
          git config --global user.name '${{ steps.user-info.outputs.user-name }}'
          git config --global user.email '${{ steps.user-info.outputs.user-email }}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: ${{ steps.user-info.outputs.user-name }}
          GIT_AUTHOR_EMAIL: ${{ steps.user-info.outputs.user-email }}
          GIT_COMMITTER_NAME: ${{ steps.user-info.outputs.user-name }}
          GIT_COMMITTER_EMAIL: ${{ steps.user-info.outputs.user-email }}
        run: npx semantic-release
